plugins {
    id 'application'
}

group = 'org.example'
version = '1.2.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'sdt.Main'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar') {
    manifest {
        attributes(
                'Main-Class': application.mainClass.get()
        )
    }
}
